force-app/main/default/objects/Flight__c/Flight__c.object-meta.xml
<CustomObject>
    <label>Flight</label>
    <nameField>
        <displayFormat>F-{00}</displayFormat>
        <label>Flight Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Flights</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Flight__c/fields/Baro_Altitude__c.field-meta.xml
<CustomField>
    <fullName>Baro_Altitude__c</fullName>
    <label>Barometric Altitude</label>
    <precision>18</precision>
    <scale>6</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Flight__c/fields/Callsign__c.field-meta.xml
<CustomField>
    <fullName>Callsign__c</fullName>
    <label>Callsign</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Flight__c/fields/ICAO24__c.field-meta.xml
<CustomField>
    <fullName>ICAO24__c</fullName>
    <externalId>true</externalId>
    <label>ICAO24</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Flight__c/fields/On_Ground__c.field-meta.xml
<CustomField>
    <fullName>On_Ground__c</fullName>
    <defaultValue>false</defaultValue>
    <label>On Ground</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Flight__c/fields/Origin_Country__c.field-meta.xml
<CustomField>
    <fullName>Origin_Country__c</fullName>
    <label>Origin Country</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Flight__c/fields/Squawk__c.field-meta.xml
<CustomField>
    <fullName>Squawk__c</fullName>
    <label>Squawk</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Flight__c/fields/Time_Position__c.field-meta.xml
<CustomField>
    <fullName>Time_Position__c</fullName>
    <label>Time Position</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Flight__c/fields/Velocity__c.field-meta.xml
<CustomField>
    <fullName>Velocity__c</fullName>
    <label>Velocity</label>
    <precision>18</precision>
    <scale>9</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Flight__c/fields/Vertical_Rate__c.field-meta.xml
<CustomField>
    <fullName>Vertical_Rate__c</fullName>
    <label>Vertical Rate</label>
    <precision>18</precision>
    <scale>8</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/FlightViewerController.cls
/**
 * Apex controller that backs Lightning components interested in Flight data.
 */
public with sharing class FlightViewerController {

	public static final Pattern commercialAirlines = Pattern.compile('[a-zA-Z]{3}(\\d*)');
	public static final Integer activityCutoffInSeconds = 600;

	@AuraEnabled
	public static List<Flight__c> getAirborneFlights() {
		// only get flight data for flights that we've heard updates from since our cutoff
		Long timestamp = System.now().getTime() / 1000 - activityCutoffInSeconds;

		return [SELECT Id, ICAO24__c, Callsign__c, Origin_Country__c, Location__Latitude__s, Location__Longitude__s, Baro_Altitude__c, Velocity__c, Vertical_Rate__c, Squawk__c FROM Flight__c WHERE On_Ground__c = FALSE AND Time_Position__c > :timestamp];
	}

	@AuraEnabled
	public static List<Flight__c> getAirborneCommercialFlights() {

		List<Flight__c> allFlights = getAirborneFlights();

		List<Flight__c> commercialFlights = new List<Flight__c>();
		for(Flight__c flight : allFlights) {
			if(String.isNotBlank(flight.Callsign__c) && commercialAirlines.matcher(flight.Callsign__c.trim()).matches())
				commercialFlights.add(flight);
		}

		return commercialFlights;
	}
}